Добавление функции add-common-films
eugenishef/java-filmorate pull request #20
Opened 2024-07-20 15:24 UTC by g0rjelin

2024-07-20 17:22 UTC, eugenishef requested changes

2024-07-20 17:22 UTC, eugenishef commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/FilmServiceImpl.java
> +                        () -> new NotFoundException(String.format("Пользователь с userId = %d не найден", userId)));
строки лучше выносить в переменные

2024-07-20 17:22 UTC, eugenishef commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/FilmServiceImpl.java
> +                        () -> new NotFoundException(String.format("Пользователь с friendId = %d не найден", friendId)));
строки лучше выносить в переменные

2024-07-20 17:22 UTC, eugenishef commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/FilmServiceImpl.java
> +                "Список общих отсортированных по популярности фильмов у пользователей с id = {} и id = {} для вывода: {}",
строки лучше выносить в переменные

2024-07-20 17:22 UTC, eugenishef commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/FilmServiceImpl.java
> +        User friend = userStorage.findUserById(friendId)
дублирующий код лучше вынести в отдельную функцию, например, findUserByIdOrThrow которая ищет пользователя или выкидывает NotFoundException

2024-07-21 10:21 UTC, g0rjelin commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/FilmServiceImpl.java
> +        User friend = userStorage.findUserById(friendId)
Использую метод UserService.getUserById, подходящий под эти требования.

2024-07-21 10:21 UTC, g0rjelin commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/FilmServiceImpl.java
> +                "Список общих отсортированных по популярности фильмов у пользователей с id = {} и id = {} для вывода: {}",
вынес в статическую переменную COMMON_FILMS_MSG

2024-07-21 10:22 UTC, g0rjelin commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/FilmServiceImpl.java
> +                        () -> new NotFoundException(String.format("Пользователь с friendId = %d не найден", friendId)));
ушло из-за использования UserService.getUserById

2024-07-21 10:22 UTC, g0rjelin commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/FilmServiceImpl.java
> +                        () -> new NotFoundException(String.format("Пользователь с userId = %d не найден", userId)));
ушло из-за использования UserService.getUserById

2024-07-22 12:41 UTC, closed without merging